Feature/opndlg 285
opendialogai/webchat pull request #271
Opened 2020-11-12 14:02 UTC by lukatabinns

od admin user to have control of access to the webchat url

2020-11-16 09:32 UTC, istos requested changes

2020-11-16 09:32 UTC, istos commented on resources/assets/js/mixins/bootstrapFunctions.js
> +  console.log(token);
I don't think this code is related to the functionality we are dealing with here, is it? Also best to remove any console logs - that is not code you want committing.

2020-11-16 09:32 UTC, istos commented on src/Http/Controllers/HistoryController.php
> +use OpenDialogAi\Webchat\WebchatSetting;
Doesn't look like there are any other changes to the HistoryController, how come you've added this here?

2020-11-16 09:32 UTC, istos commented on src/Http/Middleware/WebChatMiddleware.php
> +            Log::info('you have no permission to access this page');
The log message should be directed to the system administrator - so rather than "You have no permission...", it should be something along the lines of "Access to full page webchat denied for user xxx"

2020-11-16 09:32 UTC, istos commented on src/WebchatSetting.php
> +     * get flag for webchat setting permission
Would be good for comments to have proper punctuation. Start with a capital, end with a fullstop, etc.

2020-11-16 09:32 UTC, istos commented on src/WebchatSetting.php
> +    public static function getWebChatPermission()
Given that this is a static function and the way it is used it would make sense to make it a bit more robust. Set a return type (BOOLEAN) and name it isFullPageWebChatPubliclyAccessible - returns true is setting set to 1 and false otherwise (including the case where the setting is not set).

2020-11-16 09:32 UTC, istos commented on src/WebchatSetting.php
> +        return $val->value;
Would be good to have a generic `getWebchatSetting` function that gets passed the ID of the setting we are interested in and then we use it in a `isFullPageWebChatPubliclyAccessible` function.

2020-11-18 08:51 UTC, lukatabinns commented on resources/assets/js/mixins/bootstrapFunctions.js
> +  console.log(token);
that has been removed

2020-11-18 08:52 UTC, lukatabinns commented on src/Http/Controllers/HistoryController.php
> +use OpenDialogAi\Webchat\WebchatSetting;
That has been removed, not sure how that got there.

2020-11-18 08:54 UTC, lukatabinns commented on src/Http/Middleware/WebChatMiddleware.php
> +            Log::info('you have no permission to access this page');
I am not sure how you would get the user detail if they are not logged in. Is it not only admin can log in to the webchat settings area?

2020-11-18 08:55 UTC, lukatabinns commented on src/WebchatSetting.php
> +    public static function getWebChatPermission()
That is done.

2020-11-18 08:55 UTC, lukatabinns commented on src/WebchatSetting.php
> +        return $val->value;
That is done.

2020-11-18 09:06 UTC, lukatabinns commented on src/WebchatSetting.php
> +     * get flag for webchat setting permission
That is done

2021-01-04 13:46 UTC, stu-greenshoots commented
Closed as invalid

2021-01-04 13:46 UTC, closed without merging