Webchat sockets
opendialogai/webchat pull request #378
Opened 2022-06-24 10:55 UTC by goranambar

Implement new async endpoint and implement Broadcast channel for pushing responses to front-end.

2022-06-29 13:11 UTC, elliotmassen requested changes
This looks good - just a few questions & comments:

- One thing I haven't explored yet is how this works when the queue driver isn't `sync`. In proof-of-concept work, I did the rebinding of `'request'` (ie. `app()->instance('request', $this->request)`) because I wasn't sure if the request object would be managed properly. Would you be able to confirm this?
- I'm wondering if for now we can actually remove the `ODBroadcast` channel and it's use in `routes/channels.php`? My apologies here - I didn't initially realise that public channels can just be defined without a channel definition and class.

2022-06-30 10:57 UTC, goranambar commented
> * One thing I haven't explored yet is how this works when the queue driver isn't `sync`. In proof-of-concept work, I did the rebinding of `'request'` (ie. `app()->instance('request', $this->request)`) because I wasn't sure if the request object would be managed properly. Would you be able to confirm this?

I've checked it and this works. This works because Laravel serializes the complete request.

2022-06-30 20:36 UTC, goranambar commented on resources/assets/js/components/WebChat.vue
> +      this.channel.bind("OpenDialogAi\\Webchat\\Events\\AsyncResponse", (data) => {
I did that. You can have a friendly name for the event, instead of PHP namespace.

2022-06-30 20:36 UTC, goranambar commented on src/Jobs/ProcessAsyncRequest.php
> +        app()->instance('request', $this->request)->getContent();
ok

2022-06-30 20:38 UTC, goranambar commented on src/Jobs/ProcessAsyncRequest.php
> +            $response = null;
I have added an error event and created facilities on FE to handle it. For now is just what FE usually does on error: `We're sorry, that didn't work, please try again`, but the channel broadcasts the error message too, so it can be used in future.

2022-06-30 20:39 UTC, goranambar commented on yarn.lock
> +pusher-js@^7.1.1-beta:
I just used `yarn` for this and yarn installed this version automatically. I've reverted for the last non-beta version now.

2022-07-04 16:24 UTC, elliotmassen approved these changes

2022-07-04 16:34 UTC, merged