Prevent Illegal Characters in pusher channel name
opendialogai/webchat pull request #386
Opened 2022-08-03 09:17 UTC by stu-greenshoots

When using Pusher to send messages between front and back end, the user ID is used to create a unique channel name. In a  standard OD webchat session, the user ID will be a generated UUID and there is no problem. However, when a user email is added to the embed code eg

```                 window.openDialogSettings = {
                        url: "{{ env('APP_URL') }}",
                        mobileWidth: "1",
                        user: {
                            email:'stuart.haigh+1@opendialog.ai'
                        },
                    }
```

It is possible for illegal characters to be used in the pusher channel name https://support.pusher.com/hc/en-us/articles/4411990469265-What-Does-The-Error-Invalid-channel-name-Mean-
                    
This PR adds https://www.npmjs.com/package/md5 as dependency and uses the md5 function to convert the user id into an MD5 hash when creating the pusher channel name to avoid illegal characters being used.

It also updates the AsyncResponse to also md5 hash the user id when broadcasting

MD5 hashing was selected as it is fast, reproducible and the chance of a hash collision is low enough to not be an issue (1.47*10-29 chance of 2 hashes colliding)

2022-08-03 09:19 UTC, stu-greenshoots commented
@elliotmassen / @goranambar - This is the fix I am proposing for the Kami project where we have seen that user's using `+` in their email addresses breaks our pusher integration. 

I have been able to test as much as seeing that the MD5 is the same on both PHP and JS sides, but do not have a pusher account to hand to test. 

Could I ask that you both have a look at this solution and at least 1 of you test actually going through pusher if possible

2022-08-03 12:00 UTC, goranambar approved these changes
Stuart, this looks good and works as expected.

I've pulled webchat locally, in the kami repo, and I can see that the `user_id` is hashed and pusher channel is established with front-end. And I can see messages going back and forth with chatwoot.

However, on closing conversation from chatwoot and reopening it from OD, there's a search for existing contact into chatwoot and the problem was that the url parameter wasn't encoded, so the emails with unsupported url characters won't be found and conversation wouldn't continue.

This is fixed in [this small PR](https://github.com/opendialogai/kami/pull/12).

2022-08-04 07:26 UTC, elliotmassen approved these changes

2022-08-04 07:36 UTC, goranambar requested changes
You should also change the `AsyncErrorResponse::broadcastOn` channel name. There is a code that pushes this error when exception occurs.

2022-08-04 07:57 UTC, goranambar approved these changes

2022-08-04 09:15 UTC, merged